[package]
edition = "2021"
name = "rs058"
version = "0.1.0"
[dependencies]
actix-session = "0.5.0"
actix-files = "0.6.0"
env_logger = "0.9.0"
futures-util = "0.3.21"

[dependencies.actix-web]
version = "4"
